### ISSUE TITLE
build sh4 spark error

### ISSUE THREAD

**Issue by ahmedmoselhi** [OpenVisionE2/openvision-oe#22]
Building image for spark
ERROR: Execution of event handler 'config_reparse_eventhandler' failed
Traceback (most recent call last):
  File "/home/midoo/openpli/openpli-oe-core/openembedded-core/meta/classes/sanity.bbclass", line 973, in config_reparse_eventhandler(e=<bb.event.ConfigParsed object at 0xb44c154c>):
     python config_reparse_eventhandler() {
    >    sanity_check_conffiles(e.data)
     }
  File "/home/midoo/openpli/openpli-oe-core/openembedded-core/meta/classes/sanity.bbclass", line 572, in sanity_check_conffiles(d=<bb.data_smart.DataSmart object at 0xb462ed8c>):
                 try:
    >                bb.build.exec_func(func, d, pythonexception=True)
                 except NotImplementedError as e:
  File "/home/midoo/openpli/openpli-oe-core/bitbake/lib/bb/build.py", line 252, in exec_func(func='oecore_update_bblayers', d=<bb.data_smart.DataSmart object at 0xb462ed8c>, dirs=None, pythonexception=True):
             if runlink:
    >            bb.utils.remove(runlink)
     
  File "/home/midoo/openpli/openpli-oe-core/bitbake/lib/bb/utils.py", line 687, in remove(path='/home/midoo/openpli/openpli-oe-core/build/tmp/work/sh4-oe-linux/defaultpkgname/1.0-r0/temp/run.oecore_update_bblayers', recurse=False):
             try:
    >            os.unlink(name)
             except OSError as exc:
PermissionError: [Errno 13] Permission denied: '/home/midoo/openpli/openpli-oe-core/build/tmp/work/sh4-oe-linux/defaultpkgname/1.0-r0/temp/run.oecore_update_bblayers'

ERROR: Error parsing configuration files
Traceback (most recent call last):
  File "/home/midoo/openpli/openpli-oe-core/bitbake/lib/bb/event.py", line 106, in execute_handler(name='config_reparse_eventhandler', handler=<function config_reparse_eventhandler at 0xb4475cd4>, event=<bb.event.ConfigParsed object at 0xb44c154c>, d=<bb.data_smart.DataSmart object at 0xb462ed8c>):
         try:
    >        ret = handler(event)
         except (bb.parse.SkipRecipe, bb.BBHandledException):
  File "/home/midoo/openpli/openpli-oe-core/openembedded-core/meta/classes/sanity.bbclass", line 973, in config_reparse_eventhandler(e=<bb.event.ConfigParsed object at 0xb44c154c>):
     python config_reparse_eventhandler() {
    >    sanity_check_conffiles(e.data)
     }
  File "/home/midoo/openpli/openpli-oe-core/openembedded-core/meta/classes/sanity.bbclass", line 572, in sanity_check_conffiles(d=<bb.data_smart.DataSmart object at 0xb462ed8c>):
                 try:
    >                bb.build.exec_func(func, d, pythonexception=True)
                 except NotImplementedError as e:
  File "/home/midoo/openpli/openpli-oe-core/bitbake/lib/bb/build.py", line 252, in exec_func(func='oecore_update_bblayers', d=<bb.data_smart.DataSmart object at 0xb462ed8c>, dirs=None, pythonexception=True):
             if runlink:
    >            bb.utils.remove(runlink)
     
  File "/home/midoo/openpli/openpli-oe-core/bitbake/lib/bb/utils.py", line 687, in remove(path='/home/midoo/openpli/openpli-oe-core/build/tmp/work/sh4-oe-linux/defaultpkgname/1.0-r0/temp/run.oecore_update_bblayers', recurse=False):
             try:
    >            os.unlink(name)
             except OSError as exc:
PermissionError: [Errno 13] Permission denied: '/home/midoo/openpli/openpli-oe-core/build/tmp/work/sh4-oe-linux/defaultpkgname/1.0-r0/temp/run.oecore_update_bblayers'

Makefile:125: recipe for target 'image' failed
make: *** [image] Error 1

**Comment by aitchala** [comment]
@ahmedmoselhi  Try to remove the build folder and re-make the config again

**Comment by ahmedmoselhi** [comment]
> @ahmedmoselhi Try to remove the build folder and re-make the config again
@aitchala i deleted the build folder and now i got this:
Building image for spark
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
WARNING: /home/ahmed/openpli/openpli-oe-core/meta-qviart/recipes-bsp/linux/linux-qviart_4.2.1.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (${KERNEL_IMAGEDEST}/${KERNEL_IMAGETYPE}.gz) replaces original key FILES_kernel-image ().
WARNING: /home/ahmed/openpli/openpli-oe-core/meta-xsarius.pli5/recipes-bsp/linux/linux-xsarius_4.2.1.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (${KERNEL_IMAGEDEST}/${KERNEL_IMAGETYPE}.gz) replaces original key FILES_kernel-image ().
WARNING: /home/ahmed/openpli/openpli-oe-core/meta-vuplus/recipes-bsp/linux/linux-vuzero_3.13.5.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (${KERNEL_IMAGEDEST}/${KERNEL_IMAGETYPE}.gz) replaces original key FILES_kernel-image ().
WARNING: /home/ahmed/openpli/openpli-oe-core/meta-vuplus/recipes-bsp/linux/linux-vuzero4k_4.1.20.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (/${KERNEL_IMAGEDEST}/zImage) replaces original key FILES_kernel-image ().
WARNING: /home/ahmed/openpli/openpli-oe-core/meta-vuplus/recipes-bsp/linux/linux-vuuno_3.9.6.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (${KERNEL_IMAGEDEST}/${KERNEL_IMAGETYPE}.gz) replaces original key FILES_kernel-image ().
WARNING: /home/ahmed/openpli/openpli-oe-core/meta-vuplus/recipes-bsp/linux/linux-vuuno4kse_4.1.20.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (/${KERNEL_IMAGEDEST}/zImage) replaces original key FILES_kernel-image ().
WARNING: /home/ahmed/openpli/openpli-oe-core/meta-vuplus/recipes-bsp/linux/linux-vuuno4k_3.14.28.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (/${KERNEL_IMAGEDEST}/zImage) replaces original key FILES_kernel-image ().
WARNING: /home/ahmed/openpli/openpli-oe-core/meta-vuplus/recipes-bsp/linux/linux-vuultimo_3.9.6.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (${KERNEL_IMAGEDEST}/${KERNEL_IMAGETYPE}.gz) replaces original key FILES_kernel-image ().
WARNING: /home/ahmed/openpli/openpli-oe-core/meta-vuplus/recipes-bsp/linux/linux-vuultimo4k_3.14.28.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (/${KERNEL_IMAGEDEST}/zImage) replaces original key FILES_kernel-image ().
WARNING: /home/ahmed/openpli/openpli-oe-core/meta-vuplus/recipes-bsp/linux/linux-vusolose_3.13.5.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (${KERNEL_IMAGEDEST}/${KERNEL_IMAGETYPE}.gz) replaces original key FILES_kernel-image ().
WARNING: /home/ahmed/openpli/openpli-oe-core/meta-vuplus/recipes-bsp/linux/linux-vusolo_3.9.6.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (${KERNEL_IMAGEDEST}/${KERNEL_IMAGETYPE}.gz) replaces original key FILES_kernel-image ().
WARNING: /home/ahmed/openpli/openpli-oe-core/meta-vuplus/recipes-bsp/linux/linux-vusolo4k_3.14.28.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (/${KERNEL_IMAGEDEST}/zImage) replaces original key FILES_kernel-image ().
WARNING: /home/ahmed/openpli/openpli-oe-core/meta-vuplus/recipes-bsp/linux/linux-vusolo2_3.13.5.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (${KERNEL_IMAGEDEST}/${KERNEL_IMAGETYPE}.gz) replaces original key FILES_kernel-image ().
WARNING: /home/ahmed/openpli/openpli-oe-core/meta-vuplus/recipes-bsp/linux/linux-vuduo_3.9.6.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (${KERNEL_IMAGEDEST}/${KERNEL_IMAGETYPE}.gz) replaces original key FILES_kernel-image ().
WARNING: /home/ahmed/openpli/openpli-oe-core/meta-vuplus/recipes-bsp/linux/linux-vuduo4k_4.1.45.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (/${KERNEL_IMAGEDEST}/zImage) replaces original key FILES_kernel-image ().
WARNING: /home/ahmed/openpli/openpli-oe-core/meta-vuplus/recipes-bsp/linux/linux-vuduo2_3.13.5.bb: Variable key FILES_${KERNEL_PACKAGE_NAME}-image (${KERNEL_IMAGEDEST}/${KERNEL_IMAGETYPE}.gz) replaces original key FILES_kernel-image ().
ERROR: ExpansionError during parsing /home/ahmed/openpli/openpli-oe-core/meta-vuplus/recipes-bsp/drivers/vuplus-shutdown.bb
Traceback (most recent call last):
bb.data_smart.ExpansionError: Failure expanding variable do_fetch[file-checksums], expression was ${@bb.fetch.get_checksum_file_list(d)}  ${@get_lic_checksum_file_list(d)} which triggered exception PermissionError: [Errno 13] Permission denied: '/home/midoo'


Summary: There were 16 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
Makefile:125: recipe for target 'image' failed
make: *** [image] Error 1

**Comment by Hains** [comment]
Delete the entire openpli-oe-core build environment and start completely from scratch.
It seems your build environment is messed up. Local problem.
Spark builds without problem.
You can ignore the warning.

Test image spark.
http://www.mediafire.com/file/9edxjwrfnyyd8dw/openvision-enigma2-develop-7.0-r1-spark_usb.zip/file

**Comment by Hains** [comment]
Sorry, you can ignore this error as well.
Don't delete something for now!

```
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
make: *** [Makefile:126: image] Error 1
-e 
```

Check openpli-oe-core/build/tmp/deploy/images/spark.
