### ISSUE TITLE
problem    no   start   spark  

### ISSUE THREAD

**Issue by GM-990** [OpenVisionE2/openvision-oe#59]
close failed in file object destructor:
IOError: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/SparkVFDControl/plugin.py", line 144, in vrime
    self.prikaz()
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/SparkVFDControl/plugin.py", line 131, in prikaz
    vfd_write(clock2)
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/SparkVFDControl/plugin.py", line 35, in vfd_write
    open("/dev/dbox/oled0", "w").write(text)
IOError: [Errno 2] No such file or directory: '/dev/dbox/oled0'

**Comment by persianpros** [comment]
Thanks for the report, please compile again updating latest sources and let me know ...
