### ISSUE TITLE
standby crash  cuberevo mini

### ISSUE THREAD

**Issue by backup1977** [OpenVisionE2/openvision-oe#72]
hello friends, 
if I press the power button, I get crash problems

[eDVBFrontend0] set sequence pos 3
[eDVBFrontend0] update current switch params
[eDVBFrontend0] startTuneTimeout 5000
[eDVBFrontend0] setFrontend 1
[eDVBFrontend0] setting frontend
[evremote2 cuberevo] data[0] 0xe0, data[1] 0x a
[evremote2] KEY by code: 74 (STANDBY)
[evremote2] KEY_PRESS   - 74 7
[evremote2 cuberevo] data[0] 0xe0, data[1] 0x a
[evremote2] KEY by code: 74 (STANDBY)
[evremote2 cuberevo] data[0] 0xe0, data[1] 0x a
[evremote2] KEY by code: 74 (STANDBY)
[evremote2 cuberevo] data[0] 0xe0, data[1] 0xff
[evremote2] KEY_RELEASE - 74 gKeycode=00 nextKey=07 gNextKey=07 CAUSE: Timeout
[eDVBFrontend0] fe event: status 0, inversion off, m_tuning 1
[eDVBFrontend0] fe event: status 1, inversion off, m_tuning 2
[eDVBFrontend0] sleep 500ms
[ActionMap] Keymap 'GlobalActions' -> Action = 'power_down'
[ActionMap] Keymap 'HotkeyActions' -> Unknown action 'power'! (Typo in keymap?)
[ActionMap] Keymap 'GlobalActions' -> Action = 'power_up'
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 49, in action
  File "/usr/lib/enigma2/python/mytest.py", line 365, in powerup
    self.doAction(config.misc.hotkey.power.value)
  File "/usr/lib/enigma2/python/Components/config.py", line 1676, in __getattr__
AttributeError: power
[ePyObject] (CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap instance at 0x2c39136c>>,('GlobalActions', 'power_up')) failed)
[gRC] main thread is non-idle! display spinner!
Killed
PYTHONPATH: /usr/lib/enigma2/python
DVB_API_VERSION 5 DVB_API_VERSION_MINOR 10
ENIGMA_DEBUG_LVL=3
[MAIN] executing main

**Comment by backup1977** [comment]
it knows no, what's wrong.
I think it's the Hotkey.py because it is suitable for spark
